version: '3'

services:

  # Database
  db:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - /var/local/db_data:/var/lib/mysql
      - /var/local/db_conf:/etc/mysql/conf.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ****
      MYSQL_DATABASE: jarvis
      MYSQL_USER: jarvis_user
      MYSQL_PASSWORD: ****
    networks:
      - default

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ****
    networks:
      - default