Application:
  db-param:
    host: 192.168.1.40
    port: 3306
    db-name: jarvis
    user: jarvis_user
    password: jarvis_password

logging:
  level:
    fr.jarvis.server.ServerApplication: DEBUG
    org:
      apache: DEBUG
      springframework:
        data: DEBUG

spring:
  jpa:
    database-platform : org.hibernate.dialect.MySQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

  datasource:
    url: jdbc:mysql://${application.db-param.host}:${application.db-param.port}/${application.db-param.db-name}
    databaseName: ${application.db-param.db-name}
    username: ${application.db-param.user}
    password: ${application.db-param.password}
    driverClassName: com.mysql.cj.jdbc.Driver